package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.ListView;
import com.google.appinventor.components.runtime.Notifier;
import com.google.appinventor.components.runtime.TinyDB;
class Screen1 extends Form implements HandlesEventDispatching {
  private Label Label1;
  private HorizontalArrangement HorizontalArrangement1;
  private Label Label2;
  private TextBox TBox_ID;
  private HorizontalArrangement HorizontalArrangement2;
  private Label Label3;
  private TextBox TBox_Name;
  private HorizontalArrangement HorizontalArrangement3;
  private Label Label4;
  private TextBox TBox_Address;
  private HorizontalArrangement HorizontalArrangement4;
  private Button BTN_Save;
  private Button BTN_Update;
  private Button BTN_Delete;
  private ListView ListView1;
  private Notifier Notifier1;
  private TinyDB TinyDB1;
  protected void $define() {
    this.AlignHorizontal(3);
    this.AlignVertical(2);
    this.AppName("Firebase");
    this.Title("Screen1");
    Label1 = new Label(this);
    Label1.FontSize(30);
    Label1.Text("WEB APP");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    HorizontalArrangement1.AlignHorizontal(3);
    HorizontalArrangement1.AlignVertical(2);
    HorizontalArrangement1.Width(LENGTH_FILL_PARENT);
    Label2 = new Label(HorizontalArrangement1);
    Label2.FontBold(true);
    Label2.Text("ID");
    TBox_ID = new TextBox(HorizontalArrangement1);
    TBox_ID.Width(LENGTH_FILL_PARENT);
    TBox_ID.Hint("ENTER ID");
    TBox_ID.NumbersOnly(true);
    HorizontalArrangement2 = new HorizontalArrangement(this);
    HorizontalArrangement2.AlignHorizontal(3);
    HorizontalArrangement2.AlignVertical(2);
    HorizontalArrangement2.Width(LENGTH_FILL_PARENT);
    Label3 = new Label(HorizontalArrangement2);
    Label3.FontBold(true);
    Label3.Text("NAME");
    TBox_Name = new TextBox(HorizontalArrangement2);
    TBox_Name.Width(LENGTH_FILL_PARENT);
    TBox_Name.Hint("ENTER NAME");
    HorizontalArrangement3 = new HorizontalArrangement(this);
    HorizontalArrangement3.AlignHorizontal(3);
    HorizontalArrangement3.AlignVertical(2);
    HorizontalArrangement3.Width(LENGTH_FILL_PARENT);
    Label4 = new Label(HorizontalArrangement3);
    Label4.FontBold(true);
    Label4.Text("ADDRESS");
    TBox_Address = new TextBox(HorizontalArrangement3);
    TBox_Address.Width(LENGTH_FILL_PARENT);
    TBox_Address.Hint("ENTER ADDRESS");
    HorizontalArrangement4 = new HorizontalArrangement(this);
    HorizontalArrangement4.AlignHorizontal(3);
    HorizontalArrangement4.AlignVertical(2);
    HorizontalArrangement4.Width(LENGTH_FILL_PARENT);
    BTN_Save = new Button(HorizontalArrangement4);
    BTN_Save.FontBold(true);
    BTN_Save.Width(LENGTH_FILL_PARENT);
    BTN_Save.Text("SAVE");
    BTN_Update = new Button(HorizontalArrangement4);
    BTN_Update.FontBold(true);
    BTN_Update.Width(LENGTH_FILL_PARENT);
    BTN_Update.Text("UPDATE");
    BTN_Delete = new Button(HorizontalArrangement4);
    BTN_Delete.FontBold(true);
    BTN_Delete.Width(LENGTH_FILL_PARENT);
    BTN_Delete.Text("DELETE");
    ListView1 = new ListView(this);
    ListView1.Height(LENGTH_FILL_PARENT);
    ListView1.Width(LENGTH_FILL_PARENT);
    Notifier1 = new Notifier(this);
    TinyDB1 = new TinyDB(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}